#!/bin/sh -ef
# Copyright (C) 2021 UBports Foundation
# Dipper: nest Lomiri's Mir server on unity-system-compositor instead of
# grabbing a second standalone EGL stack (select_egl_config fails on sdm845).

export QML_NO_TOUCH_COMPRESSION=1
export MIR_SERVER_ENABLE_MIRCLIENT=1
export MIR_SERVER_PROMPT_FILE=1

if [ -z "$XDG_RUNTIME_DIR" ]; then
    XDG_RUNTIME_DIR=/run/user/$(id -u)
    export XDG_RUNTIME_DIR
fi

export MIR_SERVER_FILE="${XDG_RUNTIME_DIR}/mir_socket"
rm -f "$MIR_SERVER_FILE"
rm -f "${MIR_SERVER_FILE}_trusted"

export WAYLAND_DISPLAY=wayland-0
export QT_QPA_PLATFORM=mirserver
export LOMIRI_AS_SYSTEMD_UNIT=1
export MIR_SERVER_ENABLE_X11=1
export MIR_SERVER_XWAYLAND_PATH=/usr/libexec/Xwayland.lomiri

if [ -S /run/mir_socket ]; then
    export MIR_SERVER_HOST_SOCKET=/run/mir_socket
fi

dbus-update-activation-environment --systemd MIR_SOCKET="${MIR_SERVER_FILE}"
dbus-update-activation-environment --systemd WAYLAND_DISPLAY
if [ -n "${MIR_SERVER_HOST_SOCKET:-}" ]; then
    dbus-update-activation-environment --systemd MIR_SERVER_HOST_SOCKET="${MIR_SERVER_HOST_SOCKET}"
fi

exec ${LOMIRI_BINARY:-lomiri} "$@"
