name: CI

on:
  push:
    branches: [ main, focal/port-bootstrap ]
  pull_request:
    branches: [ main, focal/port-bootstrap ]
  repository_dispatch:
    types: [ kernel-update ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Build device tarball
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends \
            android-tools-mkbootimg bc bison build-essential ca-certificates cpio curl \
            fakeroot flex git kmod libelf-dev libssl-dev libtinfo5 lz4 python2 python3 \
            sudo unzip wget xz-utils
          sudo ln -sf python2.7 /usr/bin/python
          ./build.sh -b workdir -o out

      - name: Upload device tarball
        uses: actions/upload-artifact@v4
        with:
          path: out/*

  flashable:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: out

      - name: Build focal flashable images
        run: |
          sudo apt update
          sudo apt install -y img2simg jq sudo wget xz-utils
          git clone -b main --depth 1 \
            https://gitlab.com/ubports/porting/community-ports/halium-generic-adaptation-build-tools.git \
            build
          DEVICE="$(source deviceinfo && echo $deviceinfo_codename)"
          ./build/prepare-fake-ota.sh "out/device_${DEVICE}.tar.xz" ota
          ./build/system-image-from-ota.sh ota/ubuntu_command out

      - uses: actions/upload-artifact@v4
        with:
          name: OTA images
          path: |
            out/boot.img
            out/system.img
            out/recovery.img
